export const theme = {
  PRIMARY_COLOR: "#2aabb8",
  SECONDARY_COLOR: "",

  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,
  FONT_SIZE_MASSIVE: 24,

  FONT_WEIGHT_LIGHT: "200",
  FONT_WEIGHT_MEDIUM: "500",
  FONT_WEIGHT_BOLD: "700",

  BACKGROUND_COLOR_LIGHT: "#f0f6f7",
  CONTAINER_PADDING: 20,

  PRIMARY_FONT_FAMILY: "VarelaRound-Regular",

  PRIMARY_BACKGROUND_COLOR: "#ffffff",
  SECONDARY_BACKGROUND_COLOR: "#000000",

  PRIMARY_TEXT_BACKGROUND_COLOR: "#ffffff",
  SECONDARY_TEXT_BACKGROUND_COLOR: "#000000",
  PRIMARY_TEXT_COLOR: "#000000",
  SECONDARY_TEXT_COLOR: "#ffffff",

  PRIMARY_TEXT_INPUT_BACKGROUND_COLOR: "#ffffff",
  SECONDARY_TEXT_INPUT_BACKGROUND_COLOR: "#000000",
  PRIMARY_TEXT_INPUT_COLOR: "#000000",
  SECONDARY_TEXT_INPUT_COLOR: "#ffffff"
};